<?php

$APSAT_INFOS = array(
array("2014 AP & SAT II Science & History Programs", "", ),
array("SAT II Biology Prep. Course ", "For 9/10<sup>th</sup> grade Biology honors students", ),
array("SAT II Chemistry Prep. Course", "For 10/11<sup>th</sup>  grade Chemistry honors students", ),
array("SAT II Math IIC Prep. Course", "For 9-11<sup>th</sup>  grade Precalculus students", ),
array("AP & SAT II Biology Prep. Course", " ", ),
array("AP & SAT II Chemistry Prep. Course", " ", ),
array("AP & SAT II Physics Prep. Course", " ", ),
array("AP Euro & SAT II World History Prep. Course", "", ),
array("AP & SAT II World History Prep. Course", "", ),
array("AP & SAT II U.S. History Prep. Course ", "", ),
);

?>

