<?php

$COURS_INFOS = array(
array("2016 Fall Saturday Cours Information", "25% off before 9/11/14", ),
array("College Prep.", "9-12", array("College Essay", "USABO (Bio), USNCO (Chem), USAPhO (Physics)", "SAT II (Bio, Chem, Physics, Math)", "SAT I / PSAT (TestTakers)", "ACT, PSAT Practice Tests")),
array("H.S. Enrichment", "7-11", array("PSAT & Trigonometry", "English & Geometry", "English & Algebra")),
array("J.H.S. Enrichment", "5-8", array("English & Math Enrichment", "CTY (SCAT)")),
array("P.S. Enrichment", "3-5", array("English & Math Enrichment"))
);

?>

