<?php
$_SUMMERTOP = array(
"Grade 4 :", " ",
"Chloe Yang", "177",
"Gia Singh", "165",
"Christina Zhao", "153",
" ", " ",

"Grade 5 :", " ",
"Frank He", "183",
"Yixi Zou", "174",
"Anvit Vemuri", "148",
" ", " ",

"Grade 6 :", " ",
"Arya Tooley", "183",
"Niyanth Pohnusamy", "180",
"Khushi Patel", "176",
" ", " ",

"Grade 7 :", " ",
"Darshini Podder", "176",
"Amy Jacob", "176",
"Max Xu", "172",
"Zoe Wang", "166",
" ", " ",

"Grade 8 :", " ",
"Anshul Vemuri", "169",
"Annabel Shen", "165",
"Esther Lin", "162",
" ", " ",

"Grade 9 :", " ",
"Jimmy Zhao", "177",
"Nishanth Chinnadurai", "169",
"Benjamin Choi", "169",
"Katelyn Li", "161",
" ", " ",

"Grade 10 :", " ",
"Leo Takemaru", "161",
"Doreen Dong", "155",
"Christopher Li", "143",
" ", " ",

"Grade 11-12 :", " ",
"Uttsav Patel", "176",
"Ashley Zhang", "147",
"Andrew Kim", "143",
" ", " ",

);

?>
