<?php
$_SUMMERTOP = array(
"Grade 5 :", " ",
"Darshini Podder", "184",
"William Kim-Shoemake", "178",
"Arnav Hak", "170",
" ", " ",

"Grade 6 :", " ",
"Annabel Shen", "178",
"Dennis Jeon", "176",
"Sophia Shen", "175",
" ", " ",

"Grade 7 :", " ",
"Danny Li", "188",
"Evan Cheng", "182",
"Anoushka Dalvi", "181",
" ", " ",

"Grade 8 :", " ",
"Dylan Lai", "175",
"Michelle Liu", "169",
"Sanjana Shanmugavel", "168",
" ", " ",

"Grade 9 :", " ",
"Catherine Chen", "179",
"Vedant Singh", "177",
"Utssav Patel", "177",
"Shrey Shah", "173",
"Dhruba Podder", "173",
"Rushi Patel", "173",
" ", " ",

"Grade 10 :", " ",
"Esther Kang", "190",
"Andrew  Fang", "167",
"Zaroon Ahmad", "155",
"Ishan Gurnani", "155",
" ", " ",

"Grade 11-12 :", " ",
"Shimona Agarwal", "185",
"Kiran Shetty", "169",
"Eric Wang", "161",
" ", " ",

);

?>
