<?php
$_SUMMERTOP = array(
"Grade 5 :", " ",
"Veera  Ravichandran", "163",
"Avi Talsania", "163",
"Adeen Ahmad", "157",
"Ian Louie", "152",
" ", " ",

"Grade 6 :", " ",
"Darshini Podder", "182",
"Alex Wang", "178",
"William Kim-Shoemaker", "176",
" ", " ",

"Grade 7 :", " ",
"Annabel Shen", "179",
"Dennis Jeon", "172",
"John He", "165",
" ", " ",

"Grade 8 :", " ",
"Lynn Tian", "173",
"Benjamin Choi", "169",
"Saloni  Jhawer", "165",
"Kiersten Louie", "165",
"Alida Pahlevan", "165",
" ", " ",

"Grade 9 :", " ",
"Dylan Lai", "179",
"Yash Diwan", "175",
"Eric Wang", "169",
" ", " ",

"Grade 10 :", " ",
"Uttsav Patel", "168",
"Dhruba Podder", "158",
"Shrey Shah", "154",
"Kasra Chehrazi", "154",
" ", " ",

"Grade 11-12 :", " ",
"Matthew  Sheng", "148",
"Raymond Tian", "136",
"Jeremy  Feng", "136",
"Juhi Thomas", "126",
" ", " ",

);

?>
