<?php 

//$SCHEDULE_MENU = array( "AP & SAT II", "Regents", "ACT & SAT I", "NYS Test", "Summer School");
//$SCHEDULE_MENU = array("Fall Semester", "SAT I", "PSAT", "Summer School");
//$SCHEDULE_MENU = array("Summer School",  "AP/SAT II", "ACT", "Regents", "NYS ELA & Math Test");
//$SCHEDULE_MENU = array("TestTakers SAT/PSAT",  "CTY", "PSAT", "Fall Saturday School");
//$SCHEDULE_MENU = array("Spring Semester", "Jan. SAT Prep.", "CTY SAT & SCAT Prep.", "March SAT Prep.",  "Fall Saturday School");

$M_SUMMER = 0;
$M_SPRING = 5;
$M_FALL = 6;
$M_APSAATII = 1;
$M_ACT = 2;
$M_NYSELA = 3;
$M_REGENTS = 4;
$M_TAKERS = 7;
$M_SAT = 8;
$M_CTY = 9;
$M_PSAT = 10;
$M_AP11 = 11;
$M_SAT12 = 12;
$M_REGENTS11 = 11;
$M_SAT12 = 12;
$M_SAT13 = 13;
$M_SAT14 = 14;
include_once("../form/schedule_menu_include.inc");

/*
$S_INDEX_MENU = 
array(
	array("Fall Semester", 			1, $M_FALL),
	array("TestTakers SAT/PSAT", 	1, $M_TAKERS),
	array("AP & SAT II", 			1, $M_APSAATII),
	array("Summer School", 			1, $M_SUMMER),
	array("ACT & SAT I", 			0, $M_ACT),
	array("NYS ELA & Math Test", 	0, $M_NYSELA),
	array("Regents", 				1, $M_REGENTS),
	array("Spring Semester", 		0, $M_SPRING),

);
*/
?>