<?php
include_once ("ScheduleMenu.php");
include_once ("RegentsForm.php");
include_once ("TestTakerForm.php");
include_once ("AnnounceForm.php");
include_once ("ClassTeacherForm.php");
include_once ("AdmissionForm.php");
include_once ("SATForm.php");
include_once ("PSATForm.php");
include_once ("ACTForm.php");
include_once ("ScheduleForm.php");
include_once ("ReportForm.php");
include_once ("HomePageForm.php");
include_once ("CoursInfoForm.php");
include_once ("HomeRightForm.php");
?>