<?php 

$RegentsList = array(
array(
	array("Integrated Algebra/Algebra I", "Common Core", "Ms. D'Antone", "Mr. Inshan"), 
	"7-9", 
	array("06/20", "06/03"), 
	array(
		array("",
			"Saturday & Memorial Day", 
			"5/3, 10, 17, 24, 31", "11:00am-12:30pm",
			"5/26*, 6/7, 6/14", "9:30am-12:30pm"
		),
	),  
	"$385"
),
array(
	array("Geometry", "Mr. Echausse", "Ms.Fanelli"), 
	"9-10", 
	array("06/20"),	
	array(
		array("",
			"Saturday & Memorial Day",
			"5/3, 10, 17, 24, 31",  "9:30am-11:00am",
			"5/26*, 6/7, 6/14", "9:30am-12:30pm"
		)
	),  
	"$385"
),
array(
	array("Algebra II / Trigonometry", "Mr. Echausse"), 
	"10-11", 
	array("06/18"),
	array(
		array("",
			"Saturday & Memorial Day",
			"5/3, 10, 17, 24, 31",  "11:00am-12:30pm",
			"5/26*, 6/7, 6/14", "9:30am-12:30pm"
		)
	),  
	"$385"
),
array(
	array("Earth Science", "Mr. Barrett"), 
	"8-9", 
	array("06/19"),
	array(
		array("A", 
			"Wednesday & Memorial Day",    
			"5/7, 14, 21, 26*, 28", "5:00pm-7:00pm",
			"6/4, 6/11, 6/18", ""
		),
		array("B", 
			"Saturday, Friday & Memorial Day",    
			"5/3(s), 10(s), 16(f), 24(s)", "Saturday: 1-3pm",
			"5/26*, 31(s), 6/7(s), 13(f)", "Weekday: 4-6pm"
		)
	),
	"$385"
),                    
array(
	array("Living Environment", "Ms. Rosen"),	
	"9-10", 
	array("06/17"),
	array(
		array("",
			"Saturday & Memorial Day",
			"5/3, 10, 17, 23(f)", "Saturday: 1:00pm-3:00pm",
			"5/31, 6/7, 14, 16(m)", "Weekday:  4:30pm-6:30pm"
		)
	), 
	"$385"
),
array(
	array("Chemistry", "Mr. Strasser"), 
	"10-11", 
	array("06/24"),
	array(
		array("",
			"Tuesday, Wednesday & Saturday",
			"6/10(t), 6/11(w), 6/14(s)", "Weekday: 5-7pm",
			"6/17(t), 6/18(w), 6/21(s)", "Saturday: 1-3pm"
		)
	), 
	"$385"
),
array(
	array("Physics", "Mr. McInnes"), 
	"11-12", 
	array("06/20"),
	array(
		array("",
			"Monday, Wednesday & Thursday",
			"6/9(m),  6/11(w),  6/12(th)",  "5:00pm-7:00pm",
			"6/16(m), 6/18(w),  6/19(th)",""
		)
	),
	"$385"
),
array(
	array("Global History", "Mr. Dugan"), 
	"9-11", 
	array("06/18"),
	array(
		array("",
			"Thursday & Memorial Day",
			"5/8, 15, 22, 26*, 29, 6/5", "7:00pm-9:00pm",
			"6/12, 17(t)", "5:00pm-7:00pm"
		)
	),
	"$385"
),
array(
	array("US History", "Mr. Klaff"), 
	"11-12", 
	array("06/17"),
	array(
		array("",
			"Friday & Memorial Day",
			"5/2, 5/9, 5/16, 5/23",  "5:30pm-7:30pm",
			"5/26*, 5/30, 6/6 , 6/13",""
		)
	),
	"$385"
)
);

$RegentsNote = array(
	"Revised",
	"June 2014", 
	"5-26*  Memorial Day  - Class hour will be announced", 
);

?>
