<?php
$ACTLIST = array(
array("ACT I during 2013 Christmas Break & Weekends in January 2014", "For January ACT",
		"$210 (TESTS & SCORES ONLY)", "  $425 (TESTS & REVIEW)"),
array("12/26/2013", "9:00am-1:00pm", "FULL LENGTH PRACTICE TEST #1 xxx", ),
array("12/27/2013", "11:30am-1:00pm", "WRITING TEST ", ),
array("12/28/2013", "9:00am-1:00pm", "FULL LENGTH PRACTICE TEST #2", ),
array("12/30/2013", "11:30am-1:00pm", "CRITICAL READING TEST", ),
array("12/31/2013", "9:00am-1:00pm", "FULL LENGTH PRACTICE TEST  #3", ),
array("01/04/2014", "9:30am-1:00pm", "FULL LENGTH PRACTICE TEST  #4", ),
array("01/11/2014", "9:00am-1:00pm", "FULL LENGTH PRACTICE TEST  #5", ),
array("01/18/2014", "11:30am-1:00pm", "MATH TEST",  ),
array("01/20/2014", "9:00am-1:00pm", "FULL LENGTH PRACTICE TEST  #6", ),
);

?>