<?php

$PSATLIST = array(
array("PSAT ", "For January PSAT",
		"$150 (Test only - 6 tests);$375 (Review class only);$460 (Tests & Review class)", ""),
array("PSAT Test Date", "10/12/2011 (Wednesday) or 10/15/2011 (Saturday)", ),
array("Qualification", "for 9th, 10th or 11th graders who will take PSAT in 2011", ),
array("Practice test", "9/07, 9/14, 9/21, 9/28, 10/05 - (Wednesday 6:30pm - 9:00pm);10/10 (Columbus Day) - (Monday 9:00am - 11:30am)", ),
array("Review Class", "9/17, 9/24, 10/01, 10/08 - (Saturday 9:30am -12:30pm);10/10 (Columbus Day) - (Monday 11:30am - 2:30pm)", ),
);

?>

