<?php
$SCHEDULELIST = array(
array("2013 Chemistry Regents Review", "", ""), 
array("05/20/2013 ", "5:00pm-7:00pm", "Session 1"), 
array("05/21/2013", "4:00pm-6:00pm", "Session 2"), 
array("05/27/2013", "1:00pm-3:00pm", "Session 3"), 
array("06/01/2013", "1:00pm-3:00pm", "Session 4."), 
array("06/04/2013", "5:00pm-7:00pm", "Session 5"), 
array("06/10/2013", "4:00pm-6:00pm", "Session 6"), 
array("06/11/2013", "5:00pm-7:00pm", "Session 7"), 
);
?>