<?php

$TESTTAKER = array(	array( "08/18/2014",	"6pm-10pm",	"",	"Orientation",	"",	"Take Diagnostic SAT #1",	),
	array( "08/20/2014",	"",	"M : ",	"TestTaking Techniques",	"R/W : ",	"Sentence Completions",	),
	array( "08/25/2014",	"",	"M : ",	"Arithmetic/Algebra",	"R/W : ",	"Error ID",	),
	array( "08/27/2014",	"",	"M : ",	"TT Techniques Review",	"R/W : ",	"Reading Passages #1",	),
	array( "09/03/2014",	"",	"M : ",	"Arith/Algebra Review",	"R/W : ",	"Sentence Improvement",	),
	array( "09/04/2014",	"6pm-10pm",	"",	"Take Diagnostic SAT #2",	"",	"",	),
	array( "09/08/2014",	"",	"M : ",	"Geometry",	"R/W : ",	"Reading Passages #2",	),
	array( "09/10/2014",	"",	"M : ",	"Review Diagnostic SAT #2",	"R/W : ",	"Review Diagnostic SAT #2",	),
	array( "09/15/2014",	"",	"M : ",	"Functions and Graphs",	"R/W : ",	"Essay/Paragraph Improve",	),
	array( "09/17/2014",	"6pm-10pm",	"",	"Take Diagnostic SAT #3",	"",	"",	),
	array( "09/22/2014",	"",	"M : ",	"Geometry Review",	"R/W : ",	"Reading Comp Review",	),
	array( "09/24/2014",	"",	"M : ",	"Review Diagnostic SAT #3",	"R/W : ",	"Review Diagnostic SAT #3",	),
	array( "09/29/2014",	"",	"M : ",	"TTT Review #2",	"R/W : ",	"Complete Writing Review",	),
	array( "10/01/2014",	"6pm-8:30pm",	"",	"Take Diagnostic SAT #4",	"",	"",	),
	array( "10/06/2014",	"",	"M : ",	"Review Diagnostic SAT #4",	"R/W : ",	"Review Diagnostic SAT #4",	),
	array( "10/08/2014",	"",	"M : ",	"Complete Math Review",	"R/W : ",	"Complete Reading Review",	),
	array( "10/13/2014",	"",	"M : ",	"Practice PSAT & Review",	"R/W : ",	"Practice PSAT & Review",	),
	array( "10/15/2014",	"",	" ",	" NO CLASS!",	" ",	"",	),
);


$TESTTAKERNOTE = array(
"Fall 2014 SAT Course Schedule ",
"Sessions: 6:30pm - 9:30pm (except where indicated) ",
array("Vocabulary Quiz every Monday - 50 words per week!", "SAT: Saturday, October 11 and Saturday, November 8", "PSAT: Wednesday, October 15 and Saturday, October 18", "", "", "", "", "", "", "", "", "", "", "", ""),
array("If a session is canceled because of snow, it will be rescheduled for", "Thursday, January 3 (6:00-10:00pm); Thursday, January 23 (6:00-10:00pm);", "Thursday, February 6 (6:00-10:00pm); Thursday, February 27 (6:00-10:00pm); or", "Thursday, March 6 (6:30-9:30pm). Check our website (<a  href='www.ttprep.com'>www.ttprep.com</a>) for updates.", "", "", "", "", "", "", "", "", "", "", "", ""),
"LIA_Fall_2014_Schedule.pdf"
);

?>

