
CREATE TABLE  IF NOT EXISTS HW_TABLE (
	IDS				INTEGER			NOT NULL 	auto_increment,
	TITLE			VARCHAR(128)	NOT NULL,
	SUBJECTS		VARCHAR(64)		NOT NULL,
	CLASSES			VARCHAR(32)		NOT NULL,
	TEACHER			VARCHAR(32),
	DATES			VARCHAR(32)		NOT NULL,
	FILES			VARCHAR(512)	NOT NULL,
	COMMENTS		VARCHAR(32),
	DELETED			CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE  IF NOT EXISTS E_TABLE (
	IDS				INTEGER			NOT NULL 	auto_increment,
	TITLE			VARCHAR(1024)	NOT NULL,
	SUBJECTS		TEXT			NOT NULL,
	GROUPS			INTEGER,
	DATES			VARCHAR(32)		NOT NULL,
	SENDOK			VARCHAR(4096)	NOT NULL,
	SENDKO			VARCHAR(4096),
	CLASSES			VARCHAR(4096),
	REPORTS			INTEGER,
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE  IF NOT EXISTS REPORT_TABLE (
	IDS				INTEGER			NOT NULL 	auto_increment,
	TITLE			VARCHAR(512)	NOT NULL,
	CLASSES			VARCHAR(64)		NOT NULL,
	YEARS			VARCHAR(32),
	SEMESTERS		VARCHAR(32),
	DATES			VARCHAR(32),
	PATHS			VARCHAR(1024)	NOT NULL,
	REPORTS			VARCHAR(512)	NOT NULL,
	DIVERS			VARCHAR(1024),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;
