
CREATE TABLE IF NOT EXISTS `ttstudents` (
	IDS				INTEGER			NOT NULL 	auto_increment,
	STUDENTID 		VARCHAR(128)	NOT NULL,
	CIVIL		 	CHAR(1),
  	LASTNAME 		VARCHAR(128)	NOT NULL,
  	FIRSTNAME 		VARCHAR(128)	NOT NULL,
  	EMAIL 			VARCHAR(128)	NOT NULL,
  	GRADE 			tinyint(4) DEFAULT NULL,
  	PHONE 			varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  	MOBILE 			varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  	ANNEE 			int(11) DEFAULT NULL,
  	MATH 			int(11) DEFAULT NULL,
  	ENGLISH 		int(11) DEFAULT NULL,
  	TOTAL 			int(11) DEFAULT NULL,
  	COMMENTS 		varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  	DELETED			CHAR(1),
  	PRIMARY KEY (IDS)
  	UNIQUE KEY `STUDENTID` (`STUDENTID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;
