

CREATE TABLE  IF NOT EXISTS PSESSIONS (
	IDS				INTEGER				NOT NULL 	auto_increment,
	TEACHER			VARCHAR(128)		NOT NULL,
	SUBJECTS		VARCHAR(64),
	STUDENTID		INTEGER,
	DATES			VARCHAR(32),
	BEGINNING		VARCHAR(32),
	ENDING			VARCHAR(32),
	REQUEST			VARCHAR(32),
	GRANTED			VARCHAR(32),
	CANCEL			VARCHAR(32),
	CONFIRMC		VARCHAR(32),
	LASTMODIFY 		INTEGER,
	DELETED			CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

INSERT INTO PSESSIONS (TEACHER, SUBJECTS, STUDENTID, DATES, BEGINNING, ENDING) VALUES 
('TEACHER', 'English', '', '2011-11-11', '09:30', '12:30');

CREATE TABLE  IF NOT EXISTS NEWS_V20 (
	PID				INTEGER				NOT NULL 	auto_increment,
	UTITLE			VARCHAR(256)		NOT NULL,
	USUBJECT		VARCHAR(256),
	UTEXT			TEXT,
	UIMAGE			VARCHAR(256),
	UAUTOR			VARCHAR(64)		NOT NULL,
	UAUTORID		VARCHAR(128),
	UTIME			BIGINT,
	UGROUP			INTEGER,
	UPARENT			INTEGER,
	ULEVEL			INTEGER,
	UREAD			INTEGER,
	URESP			INTEGER,
	UTYPES          VARCHAR(256),
	PRIMARY KEY (PID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;


CREATE TABLE  IF NOT EXISTS SCHEDULE (
	ID				INTEGER				NOT NULL 	auto_increment,
	SDATE			VARCHAR(256)		NOT NULL,
	STIME			VARCHAR(256)		NOT NULL,
	TITLE1			VARCHAR(256),
	SUBJECT1		VARCHAR(256),
	TITLE2			VARCHAR(256),
	SUBJECT2		VARCHAR(256),
	TITLE3			VARCHAR(256),
	SUBJECT3		VARCHAR(256),
	DIVERS			VARCHAR(256),
  	DELETED 		INTEGER,
  	ISTITLE 		INTEGER,
	PRIMARY KEY (ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE  IF NOT EXISTS CONNECT_LIA (
	IDS				INTEGER				NOT NULL 	auto_increment,
	USERIP			VARCHAR(256)		NOT NULL,
	HOSTNAME		VARCHAR(256),
	NUMBER			BIGINT,
	FIRSTCONNECT	VARCHAR(256),
	LASTCONNECT		VARCHAR(256),
	COUNTRY			VARCHAR(256),
	DIVERS			VARCHAR(512),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS SSCORES
(
	IDS				INTEGER			NOT NULL 	auto_increment,
	STUDENTID		INTEGER			NOT NULL,
	CLASSES			VARCHAR(64)		NOT NULL,
	TEACHER			VARCHAR(128),
	TITLES			VARCHAR(128),
	SUBJECTS		VARCHAR(128),
	TYPES			VARCHAR(128),
	MATH			VARCHAR(32),
	READING			VARCHAR(32),
	WRITING			VARCHAR(32),
	TOTAL			VARCHAR(32),
	MSCORES			VARCHAR(32),
	LSCORES			VARCHAR(32),
	HSCORES			VARCHAR(32),
	DATES			VARCHAR(32),
	SEMESTER		VARCHAR(32),
	PERIODS			INTEGER,
	COMMENTS        VARCHAR(1024),
	GROUPS       	INTEGER,
	DELETED       	CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS TESTSCORES
(
	IDS				INTEGER			NOT NULL 	auto_increment,
	STUDENTID		INTEGER			NOT NULL,
	MATH			VARCHAR(32),
	ENGLISH			VARCHAR(32),
	TOTAL			VARCHAR(32),
	PRIMARY KEY (IDS),
	UNIQUE(STUDENTID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS TESTDETAILS
(
	IDS				INTEGER			NOT NULL 	auto_increment,
	STUDENTID		INTEGER			NOT NULL,
	QUESTIONS		VARCHAR(32),
	ROWSCORES		VARCHAR(32),
	PERSCORES		VARCHAR(32),
	TESTDATE		VARCHAR(32),
	ITEMS_0			VARCHAR(32),
	ITEMS_1			VARCHAR(32),
	ITEMS_2			VARCHAR(32),
	ITEMS_3			VARCHAR(32),
	ITEMS_4			VARCHAR(32),
	ITEMS_5			VARCHAR(32),
	ITEMS_6			VARCHAR(32),
	ITEMS_7			VARCHAR(32),
	ITEMS_8			VARCHAR(32),
	ITEMS_9			VARCHAR(32),
	ITEMS_10		VARCHAR(32),
	ITEMS_11		VARCHAR(32),
	ITEMS_12		VARCHAR(32),
	ITEMS_13		VARCHAR(32),
	ITEMS_14		VARCHAR(32),
	ITEMS_15		VARCHAR(32),
	ITEMS_16		VARCHAR(32),
	ITEMS_17		VARCHAR(32),
	ITEMS_18		VARCHAR(32),
	ITEMS_19		VARCHAR(32),
	DELETED		 	CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;



CREATE TABLE IF NOT EXISTS TESTSTUDENTS(
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
PSEUDO VARCHAR(32), 
EMAIL VARCHAR(128), 
PASSWD VARCHAR(10), 
CIVIL CHAR(1), 
LASTNAME VARCHAR(128), 
FIRSTNAME VARCHAR(128), 
STREET1 VARCHAR(512), 
STREET2 VARCHAR(512), 
CITY VARCHAR(256), 
POSTCODE VARCHAR(32), 
DEPARTEMENT VARCHAR(128), 
COUNTRY VARCHAR(128), 
PHONE VARCHAR(32), 
MOBILE VARCHAR(32), 
BIRTHDAY VARCHAR(32), 
CLASSES  VARCHAR(32), 
RM  VARCHAR(32), 
GRADE TINYINT, 
CURRGRADE TINYINT, 
REGISTDATE VARCHAR(32), 
LASTLOGIN VARCHAR(32), 
LASTMODIFY VARCHAR(32), 
COMMENTS VARCHAR(32), 
ISDELETED CHAR(1), 
PRIMARY KEY (IDS), 
UNIQUE(PSEUDO) 
)ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS SCORES_REF
(
	IDS				INTEGER			NOT NULL 	auto_increment,
	CLASSES			VARCHAR(64)		NOT NULL,
	GROUPS       	INTEGER			NOT NULL,
	SUBJECTS       	VARCHAR(128),
	SEMESTER       	VARCHAR(128),
	PERIODS       	INTEGER,
	DATES			VARCHAR(32),
	DELETED       	CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS STUDENTS
(
	IDS				INTEGER				NOT NULL 	auto_increment,
	PSEUDO			VARCHAR(32)			NOT NULL,
	EMAIL			VARCHAR(128),
	PASSWD			VARCHAR(10),
	CIVIL			CHAR(1),
	LASTNAME		VARCHAR(128)		NOT NULL,
	FIRSTNAME		VARCHAR(128)		NOT NULL,
	STREET1			VARCHAR(512),
	STREET2			VARCHAR(512),
	CITY			VARCHAR(28),
	POSTCODE		VARCHAR(32),
	DEPARTEMENT		VARCHAR(128),
	COUNTRY			VARCHAR(128),
	PHONE			VARCHAR(32),
	MOBILE			VARCHAR(32),
	BIRTHDAY		VARCHAR(64),
	CLASSES			VARCHAR(32),
	RM				VARCHAR(32),
	GRADE			INTEGER				NOT NULL,
	CURRGRADE		INTEGER,
	REGISTDATE      VARCHAR(32),
	LASTLOGIN       VARCHAR(32),
	LASTMODIFY      VARCHAR(32),
	COMMENTS        VARCHAR(512),
	ISDELETED       CHAR(1),
	PRIMARY KEY (IDS),
	UNIQUE(PSEUDO)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;



CREATE TABLE IF NOT EXISTS STUITION
(
	IDS				INTEGER			NOT NULL 	auto_increment,
	STUDENTID		INTEGER			NOT NULL,
	SEMESTER       	VARCHAR(128),
	PERIODS       	INTEGER,
	TUITION       	INTEGER,
	BUSES       	INTEGER,
	BOOKS       	INTEGER,
	TENNIS       	INTEGER,
	OTHERS       	INTEGER,
	PAID       		INTEGER,
	BALANCE_F       INTEGER,
	BALANCE_F_S     VARCHAR(128),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;

