
CREATE TABLE IF NOT EXISTS REGSTUDENTS
(
	IDS				INTEGER				NOT NULL 	auto_increment,
	PSEUDO			VARCHAR(32)			NOT NULL,
	EMAIL			VARCHAR(128),
	PASSWD			VARCHAR(10),
	CIVIL			CHAR(1),
	LASTNAME		VARCHAR(128)		NOT NULL,
	FIRSTNAME		VARCHAR(128)		NOT NULL,
	STREET1			VARCHAR(512),
	STREET2			VARCHAR(512),
	CITY			VARCHAR(28),
	POSTCODE		VARCHAR(32),
	DEPARTEMENT		VARCHAR(128),
	COUNTRY			VARCHAR(128),
	PHONE			VARCHAR(32),
	MOBILE			VARCHAR(32),
	BIRTHDAY		VARCHAR(64),
	CLASSES			VARCHAR(32),
	RM				VARCHAR(32),
	GRADE			INTEGER				NOT NULL,
	CURRGRADE		INTEGER,
	REGISTDATE      VARCHAR(32),
	LASTLOGIN       VARCHAR(32),
	LASTMODIFY      VARCHAR(32),
	COMMENTS        VARCHAR(512),
	ISDELETED       CHAR(1),
	PRIMARY KEY (IDS)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1;


